    # Base image
    FROM fedora:latest

    # Upgrade the system and install tuxpaint, vim, and httpd
    RUN apt-get update && apt-get install -y apache2 php curl

    # Copy local myinfo.html into the web root
    COPY data /var/www/html/data

    # Expose HTTP port
    EXPOSE 80

    # Run httpd in the foreground when the container starts
    CMD ["httpd", "-D", "FOREGROUND"]